## EDA

In [1]:
import numpy as np 
import pandas as pd

In [3]:
train = pd.read_csv('../../data/train.csv')
test = pd.read_csv('../../data/test.csv')
print("train: ", train.shape, "test: ", test.shape)

train:  (90000, 14) test:  (30000, 13)

In [6]:
print(train.isna().sum())
train.head()

id                     0
customer_id            0
last_name              0
credit_score        9556
country             6021
gender                 0
age                    0
tenure                 0
acc_balance         7257
prod_count          4863
has_card               0
is_active              0
estimated_salary       0
exit_status            0
dtype: int64

   id  customer_id  last_name  ...  is_active estimated_salary exit_status
0   0     15788291    Iredale  ...        1.0         67622.46           0
1   1     15642816        Hs?  ...        0.0        182797.86           0
2   2     15632272      T'ien  ...        1.0        170338.35           0
3   3     15685826  Hightower  ...        1.0        166476.46           0
4   4     15658032    Hopkins  ...        0.0         82526.92           0

[5 rows x 14 columns]

In [7]:
print(test.isna().sum())
test.head()

id                     0
customer_id            0
last_name              0
credit_score        3185
country             4606
gender                 0
age                    0
tenure                 0
acc_balance         5251
prod_count          1717
has_card               0
is_active              0
estimated_salary       0
dtype: int64

   id  customer_id last_name  ...  has_card is_active estimated_salary
0   0     15765283     T'ien  ...       0.0       0.0         85901.09
1   1     15660157   Macleod  ...       1.0       0.0        168023.72
2   2     15621267  Ejimofor  ...       0.0       0.0        148769.08
3   3     15651280    Nnaife  ...       1.0       0.0        172576.22
4   4     15764294    Ifeatu  ...       1.0       1.0         47832.82

[5 rows x 13 columns]